// user information

// whoami microservice
export const REQUEST_WHO_AM_I = 'REQUEST_WHO_AM_I';
export const RECEIVE_WHO_AM_I = 'RECEIVE_WHO_AM_I';
export const INVALIDATE_WHO_AM_I = 'INVALIDATE_WHO_AM_I';
export const REQUEST_INTERCOM_SETTINGS = 'REQUEST_INTERCOM_SETTINGS';
export const RECEIVE_INTERCOM_SETTINGS = 'RECEIVE_INTERCOM_SETTINGS';

// user data from account microservice
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const INVALIDATE_USER = 'INVALIDATE_USER';

// company
export const REQUEST_COMPANY = 'REQUEST_COMPANY';
export const RECEIVE_COMPANY = 'RECEIVE_COMPANY';
export const INVALIDATE_COMPANY = 'INVALIDATE_COMPANY';

// associations
export const REQUEST_ASSOCIATIONS = 'REQUEST_ASSOCIATIONS';
export const RECEIVE_ASSOCIATIONS = 'RECEIVE_ASSOCIATIONS';
export const INVALIDATE_ASSOCIATIONS = 'INVALIDATE_ASSOCIATIONS';

// employess
export const REQUEST_EMPLOYEES = 'REQUEST_EMPLOYEES';
export const RECEIVE_EMPLOYEES = 'RECEIVE_EMPLOYEES';
export const INVALIDATE_EMPLOYEES = 'INVALIDATE_EMPLOYEES';

// employee
export const REQUEST_EMPLOYEE = 'REQUEST_EMPLOYEE';
export const RECEIVE_EMPLOYEE = 'RECEIVE_EMPLOYEE';
export const CREATING_EMPLOYEE = 'CREATING_EMPLOYEE';
export const CREATED_EMPLOYEE = 'CREATED_EMPLOYEE';
export const UPDATING_EMPLOYEE = 'UPDATING_EMPLOYEE';
export const UPDATING_EMPLOYEE_FIELD = 'UPDATING_EMPLOYEE_FIELD';
export const UPDATED_EMPLOYEE = 'UPDATED_EMPLOYEE';

// employee page
export const SET_EMPLOYEE_FILTERS = 'SET_EMPLOYEE_FILTERS';

// team
export const REQUEST_TEAM = 'REQUEST_TEAM';
export const RECEIVE_TEAM = 'RECEIVE_TEAM';

// teams
export const REQUEST_TEAMS = 'REQUEST_TEAMS';
export const RECEIVE_TEAMS = 'RECEIVE_TEAMS';
export const INVALIDATE_TEAMS = 'INVALIDATE_TEAMS';

// team jobs
export const REQUEST_TEAM_JOBS = 'REQUEST_TEAM_JOBS';
export const RECEIVE_TEAM_JOBS = 'RECEIVE_TEAM_JOBS';
export const INVALIDATE_TEAM_JOBS = 'INVALIDATE_TEAM_JOBS';
export const CREATING_TEAM_JOB = 'CREATING_TEAM_JOB';
export const CREATED_TEAM_JOB = 'CREATED_TEAM_JOB';
export const UPDATING_TEAM_JOB = 'UPDATING_TEAM_JOB';
export const UPDATED_TEAM_JOB = 'UPDATED_TEAM_JOB';
export const HIDE_TEAM_JOB_FIELD_SUCCESS = 'HIDE_TEAM_JOB_FIELD_SUCCESS';

// team employees

export const REQUEST_TEAM_EMPLOYEES = 'REQUEST_TEAM_EMPLOYEES';
export const RECEIVE_TEAM_EMPLOYEES = 'RECEIVE_TEAM_EMPLOYEES';
export const INVALIDATE_TEAM_EMPLOYEES = 'INVALIDATE_TEAM_EMPLOYEES';
export const CREATING_TEAM_EMPLOYEE = 'CREATING_TEAM_EMPLOYEE';
export const CREATED_TEAM_EMPLOYEE = 'CREATED_TEAM_EMPLOYEE';

// --- scheduling ---
export const SET_SCHEDULING_FILTERS = 'SET_SCHEDULING_FILTERS';
export const SET_SCHEDULING_PARAMS = 'SET_SCHEDULING_PARAMS';
export const TOGGLE_SCHEDULING_MODAL = 'TOGGLE_SCHEDULING_MODAL';
export const UPDATE_SCHEDULING_MODAL_FORM_DATA =
  'UPDATE_SCHEDULING_MODAL_FORM_DATA';
export const CLEAR_SCHEDULING_MODAL_FORM_DATA =
  'CLEAR_SCHEDULING_MODAL_FORM_DATA';

// shift
export const REQUEST_TEAM_SHIFT = 'REQUEST_SHIFT';
export const RECEIVE_TEAM_SHIFT = 'RECEIVE_SHIFT';
export const INVALIDATE_TEAM_SHIFT = 'INVALIDATE_SHIFT';

// team shifts
export const REQUEST_TEAM_SHIFTS = 'REQUEST_TEAM_SHIFTS';
export const RECEIVE_TEAM_SHIFTS = 'RECEIVE_TEAM_SHIFTS';
export const INVALIDATE_TEAM_SHIFTS = 'INVALIDATE_TEAM_SHIFTS';
export const CREATING_TEAM_SHIFT = 'CREATING_TEAM_SHIFT';
export const CREATED_TEAM_SHIFT = 'CREATED_TEAM_SHIFT';
export const UPDATING_TEAM_SHIFT = 'UPDATING_TEAM_SHIFT';
export const UPDATED_TEAM_SHIFT = 'UPDATED_TEAM_SHIFT';
export const BULK_UPDATING_TEAM_SHIFTS = 'BULK_UPDATING_TEAM_SHIFTS';
export const BULK_UPDATED_TEAM_SHIFTS = 'BULK_UPDATED_TEAM_SHIFTS';
export const DELETING_TEAM_SHIFT = 'DELETING_TEAM_SHIFT';
export const DELETED_TEAM_SHIFT = 'DELETED_TEAM_SHIFT';

// settings
export const SET_COLOR_PICKER = 'SET_COLOR_PICKER';
export const SET_TEAM_JOB = 'SET_TEAM_JOB';
export const SET_SETTINGS_FILTERS = 'SET_SETTINGS_FILTERS';
export const UPDATING_TEAM_JOB_FIELD = 'UPDATING_TEAM_JOB_FIELD';
export const UPDATED_TEAM_JOB_FIELD = 'UPDATED_TEAM_JOB_FIELD';
export const SET_SETTINGS_NEW_TEAM_JOB = 'SET_SETTINGS_NEW_TEAM_JOB';
